import { createFeature, createReducer, on } from '@ngrx/store';
import { ProjectState } from '../interfaces';
import { ProyectoActions } from './proyecto.action';

const initialState: ProjectState = {
  projects: [],
  projectsHome: [],
  project: null,
  meta: null,
  isLoading: false,
  isLoadingMore: false,
  error: null,
  statusCode: null,
  //TODO: Images states
  imagesProject: null,
  imageLoadingProject: false,
  imageErrorProject: null,
  imageStatusCodeProject: null,
  //TODO: Technologies
  allTechnologies: [],
  isLoadingTechnologies: false,
  //TODO: Related projects
  relatedProjects: [],
  isLoadingRelatedProject: false,
  relatedErrorProject: null,
  relatedStatusCodeProject: null,
};

export const projectFeature = createFeature({
  name: 'proyectos',
  reducer: createReducer(
    initialState,
    on(ProyectoActions.getProyectos, (state, { paginado }) => ({
      ...state,
      //projects: [],
      projects: paginado.page === 1 ? [] : state.projects,
      projectsHome: [],
      project: null,
      meta: null,
      //isLoading: true,
      isLoading: paginado.page === 1,
      isLoadingMore: paginado.page > 1,
      error: null,
      statusCode: null,
      imagesProject: null,
      imageLoadingProject: false,
      imageErrorProject: null,
      imageStatusCodeProject: null,
    })),

    on(ProyectoActions.getProyectosSuccess, (state, { data }) => ({
      ...state,
      //projects: data.projects,
      projects: data.meta.currentPage === 1 ? data.projects : [...state.projects, ...data.projects],
      projectsHome: [],
      project: null,
      meta: data.meta,
      isLoading: false,
      isLoadingMore: false,
      error: null,
      statusCode: 200,
      imagesProject: null,
      imageLoadingProject: false,
      imageErrorProject: null,
      imageStatusCodeProject: null,
    })),

    on(ProyectoActions.getProyectosFailed, (state, { error, statusCode, paginado }) => ({
      ...state,
      projects: paginado?.page === 1 ? [] : state.projects,
      projectsHome: [],
      project: null,
      meta: null,
      isLoading: false,
      isLoadingMore: false,
      error,
      statusCode,
      imagesProject: null,
      imageLoadingProject: false,
      imageErrorProject: null,
      imageStatusCodeProject: null,
    })),

    on(ProyectoActions.getProyectosHome, state => ({
      ...state,
      projects: [],
      projectsHome: [],
      project: null,
      meta: null,
      isLoading: true,
      error: null,
      statusCode: null,
      imagesProject: null,
      imageLoadingProject: false,
      imageErrorProject: null,
      imageStatusCodeProject: null,
    })),

    on(ProyectoActions.getProyectosHomeSuccess, (state, { data }) => ({
      ...state,
      projects: [],
      projectsHome: data,
      project: null,
      meta: null,
      isLoading: false,
      error: null,
      statusCode: 200,
      imagesProject: null,
      imageLoadingProject: false,
      imageErrorProject: null,
      imageStatusCodeProject: null,
    })),

    on(ProyectoActions.getProyectosHomeFailed, (state, { error, statusCode }) => ({
      ...state,
      projects: [],
      projectsHome: [],
      project: null,
      meta: null,
      isLoading: false,
      error,
      statusCode,
      imagesProject: null,
      imageLoadingProject: false,
      imageErrorProject: null,
      imageStatusCodeProject: null,
    })),

    on(ProyectoActions.getProyectoBySlug, state => ({
      ...state,
      projects: [],
      projectsHome: [],
      project: null,
      meta: null,
      isLoading: true,
      error: null,
      statusCode: null,
      imagesProject: null,
      imageLoadingProject: false,
      imageErrorProject: null,
      imageStatusCodeProject: null,
    })),

    on(ProyectoActions.getProyectoBySlugSuccess, (state, { data }) => ({
      ...state,
      projects: [],
      projectsHome: [],
      project: data,
      meta: null,
      isLoading: false,
      error: null,
      statusCode: 200,
      imagesProject: null,
      imageLoadingProject: false,
      imageErrorProject: null,
      imageStatusCodeProject: null,
    })),

    on(ProyectoActions.getProyectoBySlugFailed, (state, { error, statusCode }) => ({
      ...state,
      projects: [],
      projectsHome: [],
      project: null,
      meta: null,
      isLoading: false,
      error,
      statusCode,
      imagesProject: null,
      imageLoadingProject: false,
      imageErrorProject: null,
      imageStatusCodeProject: null,
    })),

    on(ProyectoActions.getAllTechnologies, state => ({
      ...state,
      projects: [],
      projectsHome: [],
      project: null,
      meta: null,
      isLoading: false,
      error: null,
      statusCode: null,
      imagesProject: null,
      imageLoadingProject: false,
      imageErrorProject: null,
      imageStatusCodeProject: null,
      allTechnologies: [],
      isLoadingTechnologies: true,
    })),

    on(ProyectoActions.getAllTechnologiesSuccess, (state, { data }) => ({
      ...state,
      projects: [],
      projectsHome: [],
      project: null,
      meta: null,
      isLoading: false,
      error: null,
      statusCode: 200,
      imagesProject: null,
      imageLoadingProject: false,
      imageErrorProject: null,
      imageStatusCodeProject: null,
      allTechnologies: data,
      isLoadingTechnologies: false,
    })),

    on(ProyectoActions.getAllTechnologiesFailed, (state, { error, statusCode }) => ({
      ...state,
      projects: [],
      projectsHome: [],
      project: null,
      meta: null,
      isLoading: false,
      error,
      statusCode,
      imagesProject: null,
      imageLoadingProject: false,
      imageErrorProject: null,
      imageStatusCodeProject: null,
      allTechnologies: [],
      isLoadingTechnologies: false,
    })),

    on(ProyectoActions.getImagesByProjectId, state => ({
      ...state,
      imageLoadingProject: true,
      imageErrorProject: null,
      imageStatusCodeProject: null,
    })),

    on(ProyectoActions.getImagesByProjectIdSuccess, (state, { images }) => ({
      ...state,
      imageLoadingProject: false,
      imageErrorProject: null,
      imageStatusCodeProject: 200,
      imagesProject: images,
    })),

    on(ProyectoActions.getImagesByProjectIdFailure, (state, { error, statusCode }) => ({
      ...state,
      imageErrorProject: error,
      imageStatusCodeProject: statusCode,
    })),

    on(ProyectoActions.getRelatedProjectsByProjectId, state => ({
      ...state,
      relatedProjects: [],
      isLoadingRelatedProject: true,
      relatedErrorProject: null,
      relatedStatusCodeProject: null,
    })),

    on(ProyectoActions.getRelatedProjectsByProjectIdSuccess, (state, { data }) => ({
      ...state,
      isLoadingRelatedProject: false,
      relatedErrorProject: null,
      relatedStatusCodeProject: 200,
      relatedProjects: data,
    })),

    on(ProyectoActions.getRelatedProjectsByProjectIdFailure, (state, { error, statusCode }) => ({
      ...state,
      relatedErrorProject: error,
      relatedStatusCodeProject: statusCode,
    }))
  ),
});
