server {
    listen 80;
    server_name _;

    resolver 127.0.0.11 valid=10s ipv6=off;

    location /api/ {
        set $backend portfolio-web-backend-fj4t8b:4400;
        proxy_pass http://$backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /auth/ {
        set $backend portfolio-web-backend-fj4t8b:4400;
        proxy_pass http://$backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cookie_path /auth/refresh /auth/refresh;
    }

    location /file/ {
        add_header Cache-Control "no-store, private" always;

        set $backend portfolio-web-backend-fj4t8b:4400;
        proxy_pass http://$backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_intercept_errors on;
        error_page 404 = @file_not_found;
    }

    location @file_not_found {
        add_header Cache-Control "no-store, private" always;

        if ($http_sec_fetch_dest = image) {
            return 404;
        }
        proxy_pass http://localhost:4000;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://localhost:4000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}